from __future__ import annotations

import os
import platform
import sys
import time
from pathlib import Path
from typing import Any

import pandas as pd

from .config import ProjectConfig
from .io_utils import write_json, write_text, make_zip


def collect_run_manifest(config: ProjectConfig, started_at: float, completed_steps: list[str], extra: dict[str, Any] | None = None) -> dict[str, Any]:
    manifest = {
        "project": "NYC collision injury prediction",
        "author": "Alan Nemkovsky",
        "section_id": "05",
        "netid": "an1078",
        "python_version": sys.version,
        "platform": platform.platform(),
        "started_at_epoch": started_at,
        "finished_at_epoch": time.time(),
        "runtime_seconds": time.time() - started_at,
        "completed_steps": completed_steps,
        "input_paths": {
            "crashes": str(config.crashes_path),
            "vehicles": str(config.vehicles_path),
            "persons": str(config.persons_path),
        },
        "settings": {
            "chunk_size": config.chunk_size,
            "start_year": config.start_year,
            "preferred_test_year": config.preferred_test_year,
            "max_train_rows": config.max_train_rows,
            "max_test_rows": config.max_test_rows,
            "top_n_categories": config.top_n_categories,
            "enable_optional_xgboost": config.enable_optional_xgboost,
            "enable_optional_shap": config.enable_optional_shap,
            "skip_clustering": config.skip_clustering,
        },
    }
    if extra:
        manifest.update(extra)
    write_json(manifest, config.outputs_dir / "run_manifest.json")
    return manifest


def final_summary(config: ProjectConfig) -> Path:
    tables = config.outputs_dir / "tables"
    reports = config.outputs_dir / "reports"
    lines = [
        "# Final run summary for paper writing",
        "",
        "This file summarizes the outputs generated by the local pipeline. Send the full outputs zip back to ChatGPT for final paper and presentation completion.",
        "",
        "## Key files",
        "",
        "- `tables/model_metrics.csv`: main model comparison",
        "- `tables/ablation_metrics.csv`: feature-source ablation results",
        "- `tables/cluster_profiles.csv`: unsupervised cluster summaries, if clustering ran",
        "- `reports/best_model_summary.txt`: main modeling notes",
        "- `reports/data_quality_report.txt`: data quality notes, if available",
        "- `figures/`: paper-ready figures",
        "",
    ]
    for name in ["03_dataset_summary.csv", "model_metrics.csv", "ablation_metrics.csv", "cluster_profiles.csv"]:
        path = tables / name
        if path.exists():
            try:
                df = pd.read_csv(path)
                lines.append(f"## Preview: {name}")
                lines.append("")
                lines.append(df.head(12).to_markdown(index=False))
                lines.append("")
            except Exception:
                lines.append(f"- Could not preview {name}")
    summary_path = config.outputs_dir / "final_run_summary.md"
    write_text("\n".join(lines), summary_path)
    return summary_path


def zip_outputs_for_paper(config: ProjectConfig) -> Path | None:
    if not config.make_outputs_zip:
        return None
    zip_base = Path("outputs_for_paper")
    return make_zip(config.outputs_dir, zip_base)
